name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant gradlew execute permission
        run: chmod +x gradlew
      - name: Build debug APK
        run: ./gradlew assembleFdroidDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ntfy-apk
          path: app/build/outputs/apk/fdroid/debug/*.apk
